[workspace]
name = "benchmarking"
channels = ["conda-forge"]
platforms = ["linux-64", "osx-arm64"]

[dependencies]
python = ">=3.11"
numpy = "*"
pandas = "*"
matplotlib = "*"
mplfinance = "*"
pillow = "*"

[tasks]
main = "python -m scripts.main"
picture = "python -m scripts.image"